name: Docs

on:
  #push:
  #  branches-ignore:
  #    - '**'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: write

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup environment
      run: python3 -m venv doc_env
        && source doc_env/bin/activate
        && python3 -m pip install --upgrade pip
        && echo PATH=$PATH >> $GITHUB_ENV
    - name: Requirements
      run: brew install doxygen
        && brew install sphinx-doc
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install sphinx-sitemap
        && pip3 install myst-parser
    - name: Build docs
      run: source doc_env/bin/activate
        && cd docs_sphinx
        && make html
        && cd _build/html
        && touch .nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs_sphinx/_build/html # The folder the action should deploy.
